title: Jonas dos Santos Sousa 
logo: /assets/img/cv_photo.jpeg
description:
      a: Cientista de Dados
      b: Analista de Dados
      c: Graduado em Física.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
      zip_url: http://example.com/download.zip
      website: https://caerulanebulae.xyz/
