title: Jonas dos Santos Sousa 
logo: /assets/img/cv_photo.jpeg
description: Cientista de Dados | Analista de Dados | Graduado em Física.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
